<a href="https://colab.research.google.com/github/MyDearGreatTeacher/TF/blob/master/TF_1_BasicIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  TENSORFLOW 的第一堂課

資料結構:TENSOR

常數與變數

# TENSORFLOW的運算圖(Computational Graph)

開發模式:Design and run

先design模型
然後再建立session執行




# 教科書

TensorFlow Machine Learning Cookbook

Nick McClure    February 2017


https://github.com/nfmcclure/tensorflow_cookbook

# Tensor(張量)及其基本運算

## 常數 tf.constant()

## 純量 scalar

In [0]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

# Introduce tensors in tf

# Get graph handle
sess = tf.Session()

my_tensor = tf.constant(4)


sess.run(my_tensor)

4

## 一維張量

In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf

t=tf.constant([11,21,13],tf.float32)

session=tf.Session()

array=session.run(t)

print(type(array))
print(array)


<class 'numpy.ndarray'>
[11. 21. 13.]


# numpy的ndarray轉換為tensorflow 的tensor

使用tf.convert_to_tensor()函數

In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf
import numpy as np


array=np.array([1,2,3],np.float32)


t=tf.convert_to_tensor(array,tf.float32,name='t')

print(t)

sess = tf.Session()
sess.run(t)

Tensor("t_1:0", shape=(3,), dtype=float32)


array([1., 2., 3.], dtype=float32)

## 二維張量

In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf

t=tf.constant(
        [
        [1,2,3],
        [4,5,6]
        ]
        ,tf.float32)
session=tf.Session()

s=tf.shape(t)
print('張量的形狀:',session.run(s))

張量的形狀: [2 3]


# 使用random模組產生測試資料

### 建立滿足均勻分佈(最小值0，最大值10)的四維張量亂數

In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf
import matplotlib.pyplot as plt

x=tf.random_uniform([2,4,3,5],minval=0,maxval=10,dtype=tf.float32)


session=tf.Session()
array=session.run(x)
print(array)

#"為了畫出長條圖,將array轉為1個一維的ndarray"
array1d=array.reshape([-1])
plt.hist(array1d)
plt.show()


### 建立四維張量其中的值滿足正態分佈（平均值為10,標準差為1）的亂數

In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import math


sigma=1
mu=10
result=tf.random_normal([10,4,20,5],mu,sigma,tf.float32)

session=tf.Session()
array=session.run(result)

print(array)

#"將多維的ndarray轉換為一維的ndarray"
array1d=array.reshape([-1])


#""計算並顯示長條圖""
histogram,bins,patch= plt.hist(array1d,25,facecolor='gray',alpha=0.5,normed=True)

x=np.arange(5,15,0.01)
y=1.0/(math.sqrt(2*np.pi)*sigma)*np.exp(-np.power(x-mu,2.0)/(2*math.pow(sigma,2)))
plt.plot(x,y)
plt.show()


# 變數 tf.Variable

In [0]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

# Introduce tensors in tf

# Get graph handle
sess = tf.Session()

my_tensor = tf.zeros([1,20])

# Declare a variable
my_var = tf.Variable(tf.zeros([1,20]))

# Different kinds of variables
row_dim = 2
col_dim = 3 

# Zero initialized variable
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))

# One initialized variable
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))

# shaped like other variable
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(ones_similar.initializer)
sess.run(zero_similar.initializer)


##  PlaceHolder 佔位符

Inserts a placeholder for a tensor that will be always fed.

https://www.tensorflow.org/api_docs/python/tf/placeholder

tf.placeholder

tf.placeholder(
    dtype,
    shape=None,
    name=None
)

Defined in tensorflow/python/ops/array_ops.py.



Important: This tensor will produce an error if evaluated. Its value must be fed using the feed_dict optional argument to Session.run(), Tensor.eval(), or Operation.run().

What's the difference between tf.placeholder and tf.Variable?

https://stackoverflow.com/questions/36693740/whats-the-difference-between-tf-placeholder-and-tf-variable

In [0]:
# y=w*x   W===3*2  x可以是2*1,  2*2,  2*3　最後執行運算時再帶入真正的值

# -*- coding: utf-8 -*-
import tensorflow as tf
import numpy as np

session=tf.Session()

x=tf.placeholder(tf.float32,[2,None],name='x')


w=tf.constant(
        [
        [1,2],
        [3,4],
        [5,6]
        ],tf.float32
        )

y=tf.matmul(w,x)


result1=session.run(y,feed_dict={x:np.array([[2,1],[1,2]],np.float32)})
print(result1)


result2=session.run(y,feed_dict={x:np.array([[-1],[2]],np.float32)})
print(result2)


[[ 4.  5.]
 [10. 11.]
 [16. 17.]]
[[3.]
 [5.]
 [7.]]


# 張量的運算

張量有許多運算

底下以範例說明最常用的運算

### 範例:加總運算tf.reduce_sum()

Reduction運算

In [0]:
import tensorflow as tf

session=tf.Session()

#"二維張量"
value2d=tf.constant(
        [
        [5,1,4,2],
        [3,9,5,7]
                ],tf.float32
        )

#"計算沿0軸方向上的和"
sum0=tf.reduce_sum(value2d,axis=0)
print("沿 0 軸方向上的和:")
print(session.run(sum0))


#"計算沿1軸方向上的和"
sum1=tf.reduce_sum(value2d,axis=1)
print("沿 1 軸方向上的和:")
print(session.run(sum1))

#"計算沿(0,1)平面上的和"
sum01=tf.reduce_sum(value2d,axis=(0,1))
print("沿 (0,1) 平面上的和:")
print(session.run(sum01))


沿 0 軸方向上的和:
[ 8. 10.  9.  9.]
沿 1 軸方向上的和:
[12. 24.]
沿 (0,1) 平面上的和:
36.0


## 範例一:求 3+6=?

In [0]:
import tensorflow as tf

session=tf.Session()

a = tf.constant(3)
b = tf.constant(6)
c=a+b

print(session.run(c))

9


## 範例二: x=9, y=x**2,f=3y-5x+1求f=?


In [4]:
import tensorflow as tf

#reset_graph()

x = tf.Variable(3, name="x")
y = tf.Variable(x**2, name="y")
f = 3*y-5*x+1

sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)

sess.close()

13


In [0]:
import tensorflow as tf

#reset_graph()

x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x**2+3*x*y + y + 2

sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)

sess.close()

## 範例三:矩陣相加(兩種寫法)


result=tf.add(value1,value2)

result=value1+value2

print(session.run(result))

In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf

session=tf.Session()


value1=tf.constant(
        [
         [1,2,3],
         [4,5,6]
        ],tf.float32)

value2=tf.constant([
        [10],
        [20]
        ],tf.float32)

result=tf.add(value1,value2)

print(session.run(result))

[[11. 12. 13.]
 [24. 25. 26.]]


In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf

session=tf.Session()


value1=tf.constant(
        [
         [1,2,3],
         [4,5,6]
        ],tf.float32)

value2=tf.constant([10,20,30],tf.float32)

result=tf.add(value1,value2)

print(session.run(result))

[[11. 22. 33.]
 [14. 25. 36.]]


## 範例四:矩陣transpose運算

tf.transpose(
    a,
    perm=None,
    name='transpose',
    conjugate=False
)

https://www.tensorflow.org/api_docs/python/tf/transpose

In [0]:
import tensorflow as tf

x = [[1,2,3],[4,5,6]]
x = tf.convert_to_tensor(x)
xtrans = tf.transpose(x)

with tf.Session() as sess:
    print(sess.run(xtrans))

[[1 4]
 [2 5]
 [3 6]]


## 範例五:矩陣相乘

特別注意兩種不同乘法

 element-wise乘法
 
 內積乘法

In [0]:
import tensorflow as tf

mat1 = tf.constant([[4, 5, 6],[3,2,1]])
mat2 = tf.constant([[7, 8, 9],[10, 11, 12]])

# hadamard product (element wise)
mult = tf.multiply(mat1, mat2)

# dot product (no. of rows = no. of columns)
dotprod = tf.matmul(mat1, tf.transpose(mat2))

with tf.Session() as sess:
    print(sess.run(mult))
    print(sess.run(tf.transpose(mat2)))
    print(sess.run(dotprod))

In [0]:
# convert matrices to tensor objects
import numpy as np
import tensorflow as tf

# create a 2x2 matrix in various forms
matrix1 = [[1.0, 2.0], [3.0, 40]]
matrix2 = np.array([[1.0, 2.0], [3.0, 40]], dtype=np.float32)
matrix3 = tf.constant([[1.0, 2.0], [3.0, 40]])

print(type(matrix1))
print(type(matrix2))
print(type(matrix3))

print(matrix1)
print(matrix2)
print(matrix3)

tensorForM1 = tf.convert_to_tensor(matrix1, dtype=tf.float32)
tensorForM2 = tf.convert_to_tensor(matrix2, dtype=tf.float32)
tensorForM3 = tf.convert_to_tensor(matrix3, dtype=tf.float32)

print(type(tensorForM1))
print(type(tensorForM2))
print(type(tensorForM3))

# 常用的常數向量建構函數

tf.constant() 創造常數張量

tf.zeros() ：建構內容數值皆為 0 的常數張量

tf.ones() ：建構內容數值皆為 1 的常數張量

tf.fill() ：建構內容數值皆為特定值的常數張量

tf.range() ：建構內容數值為 (start, limit, delta) 數列的常數張量

tf.random_normal() ：建構內容數值為符合常態分佈數列的常數張量

tf.random_uniform() ：建構內容數值為符合均勻分佈數列的常數張量

zeros = tf.zeros((2, 2))

ones = tf.ones((2, 2))

fills = tf.fill((2, 2), 5)

ranges = tf.reshape(tf.range(1, 9, 2), (2, 2))

normals = tf.random_normal((2, 2))

uniforms = tf.random_uniform((2, 2))

In [0]:
import numpy as np
import tensorflow as tf

print("NumPy:")
print(np.zeros((2, 2)))
print(np.ones((2, 2)))
print(np.full((2, 2), 5))
print(np.arange(1, 9, 2).reshape(2, 2))
print(np.random.normal(size=(2, 2)))
print(np.random.uniform(size=(2, 2)))
print("\n")
print("TensorFlow:")
zeros = tf.zeros((2, 2))
ones = tf.ones((2, 2))
fills = tf.fill((2, 2), 5)
ranges = tf.reshape(tf.range(1, 9, 2), (2, 2))
normals = tf.random_normal((2, 2))
uniforms = tf.random_uniform((2, 2))
initializations = [zeros, ones, fills, ranges, normals, uniforms, ]
with tf.Session() as sess:
  for i in initializations:
    print(sess.run(i))

# 張量運算 Tensor operations




### tf.reshape()

In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf

session=tf.Session()


#"2行3列2深度的三維張量"
t3d=tf.constant(
        [
        [[1,2],[4,5],[6,7]],
        [[8,9],[10,11],[12,13]]
        ],tf.float32
        )

#"改變形狀為4行1列3深度的三維張量"
t1 = tf.reshape(t3d,[4,1,-1])

print(session.run(t1))


[[[ 1.  2.  4.]]

 [[ 5.  6.  7.]]

 [[ 8.  9. 10.]]

 [[11. 12. 13.]]]


## tf.slice()切片運算


In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf


t1=tf.constant([1,2,3,4,5],tf.float32)

#"從t1的第1個位置開始,取長度為3的區域"
t=tf.slice(t1,[1],[3])

session=tf.Session()

print(session.run(t))


[2. 3. 4.]


# 測驗

In [0]:
import tensorflow as tf

x = [[1,2,3],[4,5,6]]
x = tf.convert_to_tensor(x)
xtrans1 = tf.transpose(x)
xtrans2 = tf.transpose(x, perm=[0,1])
xtrans3 = tf.transpose(x, perm=[1,0])

with tf.Session() as sess:
    print(sess.run(xtrans1))
    print(sess.run(xtrans2))
    print(sess.run(xtrans3))

In [0]:
import tensorflow as tf

y=([[[1,2,3],[6,5,4]],[[4,5,6],[3,6,3]]])
y = tf.convert_to_tensor(y)
ytrans = tf.transpose(y, perm=[0, 2, 1])
ytrans2 = tf.transpose(y, perm=[0, 1, 2])

with tf.Session() as sess:
    print(sess.run(ytrans))
    print(sess.run(ytrans2))

In [0]:
# -*- coding: utf-8 -*-
import tensorflow as tf

session=tf.Session()

#"三維張量"
value3d=tf.constant(
        [
        [[2,5],[3,3],[8,2]],
        [[6,1],[1,2],[5,4]],
        [[7,9],[2,-3],[-1,3]]
        ],tf.float32
        )

#"計算沿 0 方向上的和"
sum0=tf.reduce_sum(value3d,axis=0)


print(session.run(sum0))

In [0]:
#兩個張量的疊加運算tf.stack()

# -*- coding: utf-8 -*-
import tensorflow as tf


t1=tf.constant([1,2,3],tf.float32)
t2=tf.constant([7,8,9],tf.float32)

t=tf.stack([t1,t2],0)
t1=tf.stack([t1,t2],1)

session=tf.Session()
print(session.run(t))
print(session.run(t1))

[[1. 2. 3.]
 [7. 8. 9.]]
[[1. 7.]
 [2. 8.]
 [3. 9.]]


In [0]:
#兩個張量的連接運算tf.concat()

import tensorflow as tf

session=tf.Session()

t1=tf.constant(
        [
        [1,2,3],
        [4,5,6]
        ],tf.float32
        )
t2=tf.constant(
        [
        [11,12,13],
        [24,25,26]
        ],tf.float32
        )

Concat1=tf.concat([t1,t2],axis=0)
Concat2=tf.concat([t1,t2],axis=1)

print(session.run(Concat1))
print(session.run(Concat2))


In [0]:
import tensorflow as tf

session=tf.Session()

value2d=tf.constant(
        [
         [5,1,4,2],
         [3,9,5,7]
                ],tf.float32
        )

#"求沿1方向上，即每一行的最大值的位置索引"
result=tf.argmax(value2d,axis=1)
result2=tf.argmax(value2d,axis=0)

#result3=tf.max(value2d,axis=1)
#result4=tf.max(value2d,axis=0)

print(session.run(result))
print(session.run(result2))
#print(session.run(result3))
#print(session.run(result4))